Fix #1266
Equipment-and-Tool-Institute/j1939-84 pull request #1290
Opened 2023-12-01 04:04 UTC by karysg

@battjt

2023-12-01 14:33 UTC, battjt requested changes

2023-12-01 14:33 UTC, battjt commented on src/org/etools/j1939_84/controllers/part01/Part01Step11Controller.java
> +                .stream().filter(p -> p.getKmWhileMILIsActivated() != NOT_AVAILABLE ||
This is filtering out any packet that has any N/A values.  In the case of a packet with all useful data, except for one N/A, this change will ignore the signals that should be considered.  Instead, all the packets should be considered, but any N/A signal values should be ignored.  (right?)

2023-12-01 17:26 UTC, karysg commented on src/org/etools/j1939_84/controllers/part01/Part01Step11Controller.java
> +                .stream().filter(p -> p.getKmWhileMILIsActivated() != NOT_AVAILABLE ||
It's a pass filter, if any of the checked values != NOT_AVAILABLE it will be included in globalPackets.

2024-01-23 03:19 UTC, karysg commented
@battjt It would probably be best to review this together on Wednesday.

2024-01-24 20:30 UTC, merged