Fix #949 - Correct DS DM19 call
Equipment-and-Tool-Institute/j1939-84 pull request #951
Opened 2021-04-13 16:56 UTC by mmschaefer

Fix #949 - Update the controller to actually do a DS call to the modules and corrected to test to expect results created by the correct call.

2021-04-13 18:18 UTC, gumbelmj requested changes
Need to also request packets from those that responded to the global request

2021-04-13 18:18 UTC, gumbelmj commented on src/org/etools/j1939_84/controllers/part01/Part01Step07Controller.java
>          // ECUs that responded to global DM19).
This collection of addresses needs to also include the addresses of the modules that responded to the global request.

2021-04-15 12:05 UTC, gumbelmj approved these changes

2021-04-15 12:23 UTC, merged

2021-04-19 15:18 UTC, battjt reviewed
How does this handle "Destination Specific (DS) DM19 to each OBD ECU **(plus all ECUs that responded to global DM19).**"?

2021-04-19 15:25 UTC, gumbelmj commented
```
Stream.concat(getDataRepository().getObdModuleAddresses().stream(),
                                       globalPackets.stream().map(ParsedPacket::getSourceAddress))
                               .distinct()
```
Merges together the addresses from the OBD Modules addresses and the addresses from the modules that responding to the global request.